### ISSUE TITLE
[2022-04-15] 문제 번호

### ISSUE THREAD

**Issue by sukyung99** [win9612/ssafy-d6-study#131]
## 2022/04/15

분류  | 번호 | 문제 이름 | 난이도
|:-------:|:----:|:---------:|:-----:|
| BOJ | [19236](https://www.acmicpc.net/problem/19236) | [청소년 상어](https://www.acmicpc.net/problem/19236) | 상 |
| BOJ | [18428](https://www.acmicpc.net/problem/18428) | [감시 피하기](https://www.acmicpc.net/problem/18428) | 하 |

### 다음 문제 당번
```diff
++승원++
```
### 문제 로테이션
[ 승원 - 화연 - 다빈 - 갑경 - 윤혁 - 민규 - 상협  - 수경]

**Comment by choiswonspec** [comment]
## 2022/04/19

분류  | 번호 | 문제 이름 | 난이도
|:-------:|:----:|:---------:|:-----:|
| BOJ | [20181](https://www.acmicpc.net/problem/20181) | [호석 애벌레](https://www.acmicpc.net/problem/20181) | 상 |
| BOJ | [9084](https://www.acmicpc.net/problem/9084) | [동전](https://www.acmicpc.net/problem/9084) | 하 |


### 다음 문제 당번
```diff
++화연++
```
### 문제 로테이션
[ 화연 - 다빈 - 갑경 - 윤혁 - 민규 - 상협  - 수경 - 승원]
