### ISSUE TITLE
[2022-03-11] 문제 번호

### ISSUE THREAD

**Issue by parksanghyeop** [win9612/ssafy-d6-study#77]
## 2022/03/08

분류  | 번호 | 문제 이름 | 난이도
|:-------:|:----:|:---------:|:-----:|
| BOJ| [20327](https://www.acmicpc.net/problem/20327) | [배열 돌리기 6](https://www.acmicpc.net/problem/20327) | 상 |
| BOJ | [17073](https://www.acmicpc.net/problem/17073) | [나무 위의 빗물](https://www.acmicpc.net/problem/17073) | 중 |
| BOJ | [16918](https://www.acmicpc.net/problem/16918) | [붐버맨](https://www.acmicpc.net/problem/16918) | 하 |

### 다음 문제 당번
화연 - 다빈 - 갑경 - 민규 - 윤혁 - 상협 - 승원

**Comment by parksanghyeop** [comment]
상 - (HTML 파싱) : 문자열을 이용한 구현문제입니다.

중 - (성곽) : 그래프  탐색 문제입니다.

하 - (부동산 다툼) : 트리 문제입니다.

**Comment by choiswonspec** [comment]
## 2022/03/15

분류  | 번호 | 문제 이름 | 난이도
|:-------:|:----:|:---------:|:-----:|
| BOJ| [20327](https://www.acmicpc.net/problem/20327) | [배열 돌리기 6](https://www.acmicpc.net/problem/20327) | 상 |
| BOJ | [17073](https://www.acmicpc.net/problem/17073) | [나무 위의 빗물](https://www.acmicpc.net/problem/17073) | 중 |
| BOJ | [16918](https://www.acmicpc.net/problem/16918) | [붐버맨](https://www.acmicpc.net/problem/16918) | 하 |


### 다음 문제 당번
화연 - 다빈 - 갑경 - 민규 - 윤혁 - 상협 - 승원

**Comment by choiswonspec** [comment]
상 - 배열 돌리기 6 : 구현

중 - 나무 위의 빗물 : 트리

하 - 붐버맨 : 그래프 탐색
